// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: urgent.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "urgent.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ydpb {

namespace {

const ::google::protobuf::Descriptor* Pos_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Pos_reflection_ = NULL;
const ::google::protobuf::Descriptor* Urgent_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Urgent_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_urgent_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_urgent_2eproto() {
  protobuf_AddDesc_urgent_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "urgent.proto");
  GOOGLE_CHECK(file != NULL);
  Pos_descriptor_ = file->message_type(0);
  static const int Pos_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pos, pos_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pos, pos_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pos, pos_z_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pos, qua_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pos, qua_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pos, qua_z_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pos, qua_w_),
  };
  Pos_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Pos_descriptor_,
      Pos::default_instance_,
      Pos_offsets_,
      -1,
      -1,
      -1,
      sizeof(Pos),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pos, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pos, _is_default_instance_));
  Urgent_descriptor_ = file->message_type(1);
  static const int Urgent_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Urgent, temp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Urgent, cpos_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Urgent, hpos_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Urgent, bat_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Urgent, tid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Urgent, err_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Urgent, last_updated_),
  };
  Urgent_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Urgent_descriptor_,
      Urgent::default_instance_,
      Urgent_offsets_,
      -1,
      -1,
      -1,
      sizeof(Urgent),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Urgent, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Urgent, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_urgent_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Pos_descriptor_, &Pos::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Urgent_descriptor_, &Urgent::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_urgent_2eproto() {
  delete Pos::default_instance_;
  delete Pos_reflection_;
  delete Urgent::default_instance_;
  delete Urgent_reflection_;
}

void protobuf_AddDesc_urgent_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_urgent_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2ftimestamp_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014urgent.proto\022\004ydpb\032\037google/protobuf/ti"
    "mestamp.proto\"n\n\003Pos\022\r\n\005pos_x\030\001 \001(\002\022\r\n\005p"
    "os_y\030\002 \001(\002\022\r\n\005pos_z\030\003 \001(\002\022\r\n\005qua_x\030\004 \001(\002"
    "\022\r\n\005qua_y\030\005 \001(\002\022\r\n\005qua_z\030\006 \001(\002\022\r\n\005qua_w\030"
    "\007 \001(\002\"\241\001\n\006Urgent\022\014\n\004temp\030\001 \003(\002\022\027\n\004cpos\030\002"
    " \003(\0132\t.ydpb.Pos\022\027\n\004hpos\030\003 \003(\0132\t.ydpb.Pos"
    "\022\013\n\003bat\030\004 \001(\002\022\013\n\003tid\030\005 \001(\005\022\013\n\003err\030\006 \001(\005\022"
    "0\n\014last_updated\030\007 \001(\0132\032.google.protobuf."
    "Timestampb\006proto3", 337);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "urgent.proto", &protobuf_RegisterTypes);
  Pos::default_instance_ = new Pos();
  Urgent::default_instance_ = new Urgent();
  Pos::default_instance_->InitAsDefaultInstance();
  Urgent::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_urgent_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_urgent_2eproto {
  StaticDescriptorInitializer_urgent_2eproto() {
    protobuf_AddDesc_urgent_2eproto();
  }
} static_descriptor_initializer_urgent_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Pos::kPosXFieldNumber;
const int Pos::kPosYFieldNumber;
const int Pos::kPosZFieldNumber;
const int Pos::kQuaXFieldNumber;
const int Pos::kQuaYFieldNumber;
const int Pos::kQuaZFieldNumber;
const int Pos::kQuaWFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Pos::Pos()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ydpb.Pos)
}

void Pos::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Pos::Pos(const Pos& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ydpb.Pos)
}

void Pos::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  pos_x_ = 0;
  pos_y_ = 0;
  pos_z_ = 0;
  qua_x_ = 0;
  qua_y_ = 0;
  qua_z_ = 0;
  qua_w_ = 0;
}

Pos::~Pos() {
  // @@protoc_insertion_point(destructor:ydpb.Pos)
  SharedDtor();
}

void Pos::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Pos::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Pos::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Pos_descriptor_;
}

const Pos& Pos::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_urgent_2eproto();
  return *default_instance_;
}

Pos* Pos::default_instance_ = NULL;

Pos* Pos::New(::google::protobuf::Arena* arena) const {
  Pos* n = new Pos;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Pos::Clear() {
// @@protoc_insertion_point(message_clear_start:ydpb.Pos)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(Pos, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Pos*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(pos_x_, qua_w_);

#undef ZR_HELPER_
#undef ZR_

}

bool Pos::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ydpb.Pos)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float pos_x = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &pos_x_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_pos_y;
        break;
      }

      // optional float pos_y = 2;
      case 2: {
        if (tag == 21) {
         parse_pos_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &pos_y_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_pos_z;
        break;
      }

      // optional float pos_z = 3;
      case 3: {
        if (tag == 29) {
         parse_pos_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &pos_z_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(37)) goto parse_qua_x;
        break;
      }

      // optional float qua_x = 4;
      case 4: {
        if (tag == 37) {
         parse_qua_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &qua_x_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(45)) goto parse_qua_y;
        break;
      }

      // optional float qua_y = 5;
      case 5: {
        if (tag == 45) {
         parse_qua_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &qua_y_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(53)) goto parse_qua_z;
        break;
      }

      // optional float qua_z = 6;
      case 6: {
        if (tag == 53) {
         parse_qua_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &qua_z_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(61)) goto parse_qua_w;
        break;
      }

      // optional float qua_w = 7;
      case 7: {
        if (tag == 61) {
         parse_qua_w:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &qua_w_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ydpb.Pos)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ydpb.Pos)
  return false;
#undef DO_
}

void Pos::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ydpb.Pos)
  // optional float pos_x = 1;
  if (this->pos_x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->pos_x(), output);
  }

  // optional float pos_y = 2;
  if (this->pos_y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->pos_y(), output);
  }

  // optional float pos_z = 3;
  if (this->pos_z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->pos_z(), output);
  }

  // optional float qua_x = 4;
  if (this->qua_x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->qua_x(), output);
  }

  // optional float qua_y = 5;
  if (this->qua_y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->qua_y(), output);
  }

  // optional float qua_z = 6;
  if (this->qua_z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->qua_z(), output);
  }

  // optional float qua_w = 7;
  if (this->qua_w() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->qua_w(), output);
  }

  // @@protoc_insertion_point(serialize_end:ydpb.Pos)
}

::google::protobuf::uint8* Pos::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ydpb.Pos)
  // optional float pos_x = 1;
  if (this->pos_x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->pos_x(), target);
  }

  // optional float pos_y = 2;
  if (this->pos_y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->pos_y(), target);
  }

  // optional float pos_z = 3;
  if (this->pos_z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->pos_z(), target);
  }

  // optional float qua_x = 4;
  if (this->qua_x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->qua_x(), target);
  }

  // optional float qua_y = 5;
  if (this->qua_y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->qua_y(), target);
  }

  // optional float qua_z = 6;
  if (this->qua_z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->qua_z(), target);
  }

  // optional float qua_w = 7;
  if (this->qua_w() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->qua_w(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:ydpb.Pos)
  return target;
}

int Pos::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:ydpb.Pos)
  int total_size = 0;

  // optional float pos_x = 1;
  if (this->pos_x() != 0) {
    total_size += 1 + 4;
  }

  // optional float pos_y = 2;
  if (this->pos_y() != 0) {
    total_size += 1 + 4;
  }

  // optional float pos_z = 3;
  if (this->pos_z() != 0) {
    total_size += 1 + 4;
  }

  // optional float qua_x = 4;
  if (this->qua_x() != 0) {
    total_size += 1 + 4;
  }

  // optional float qua_y = 5;
  if (this->qua_y() != 0) {
    total_size += 1 + 4;
  }

  // optional float qua_z = 6;
  if (this->qua_z() != 0) {
    total_size += 1 + 4;
  }

  // optional float qua_w = 7;
  if (this->qua_w() != 0) {
    total_size += 1 + 4;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Pos::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ydpb.Pos)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Pos* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Pos>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ydpb.Pos)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ydpb.Pos)
    MergeFrom(*source);
  }
}

void Pos::MergeFrom(const Pos& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ydpb.Pos)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.pos_x() != 0) {
    set_pos_x(from.pos_x());
  }
  if (from.pos_y() != 0) {
    set_pos_y(from.pos_y());
  }
  if (from.pos_z() != 0) {
    set_pos_z(from.pos_z());
  }
  if (from.qua_x() != 0) {
    set_qua_x(from.qua_x());
  }
  if (from.qua_y() != 0) {
    set_qua_y(from.qua_y());
  }
  if (from.qua_z() != 0) {
    set_qua_z(from.qua_z());
  }
  if (from.qua_w() != 0) {
    set_qua_w(from.qua_w());
  }
}

void Pos::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ydpb.Pos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Pos::CopyFrom(const Pos& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ydpb.Pos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Pos::IsInitialized() const {

  return true;
}

void Pos::Swap(Pos* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Pos::InternalSwap(Pos* other) {
  std::swap(pos_x_, other->pos_x_);
  std::swap(pos_y_, other->pos_y_);
  std::swap(pos_z_, other->pos_z_);
  std::swap(qua_x_, other->qua_x_);
  std::swap(qua_y_, other->qua_y_);
  std::swap(qua_z_, other->qua_z_);
  std::swap(qua_w_, other->qua_w_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Pos::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Pos_descriptor_;
  metadata.reflection = Pos_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Pos

// optional float pos_x = 1;
void Pos::clear_pos_x() {
  pos_x_ = 0;
}
 float Pos::pos_x() const {
  // @@protoc_insertion_point(field_get:ydpb.Pos.pos_x)
  return pos_x_;
}
 void Pos::set_pos_x(float value) {
  
  pos_x_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Pos.pos_x)
}

// optional float pos_y = 2;
void Pos::clear_pos_y() {
  pos_y_ = 0;
}
 float Pos::pos_y() const {
  // @@protoc_insertion_point(field_get:ydpb.Pos.pos_y)
  return pos_y_;
}
 void Pos::set_pos_y(float value) {
  
  pos_y_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Pos.pos_y)
}

// optional float pos_z = 3;
void Pos::clear_pos_z() {
  pos_z_ = 0;
}
 float Pos::pos_z() const {
  // @@protoc_insertion_point(field_get:ydpb.Pos.pos_z)
  return pos_z_;
}
 void Pos::set_pos_z(float value) {
  
  pos_z_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Pos.pos_z)
}

// optional float qua_x = 4;
void Pos::clear_qua_x() {
  qua_x_ = 0;
}
 float Pos::qua_x() const {
  // @@protoc_insertion_point(field_get:ydpb.Pos.qua_x)
  return qua_x_;
}
 void Pos::set_qua_x(float value) {
  
  qua_x_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Pos.qua_x)
}

// optional float qua_y = 5;
void Pos::clear_qua_y() {
  qua_y_ = 0;
}
 float Pos::qua_y() const {
  // @@protoc_insertion_point(field_get:ydpb.Pos.qua_y)
  return qua_y_;
}
 void Pos::set_qua_y(float value) {
  
  qua_y_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Pos.qua_y)
}

// optional float qua_z = 6;
void Pos::clear_qua_z() {
  qua_z_ = 0;
}
 float Pos::qua_z() const {
  // @@protoc_insertion_point(field_get:ydpb.Pos.qua_z)
  return qua_z_;
}
 void Pos::set_qua_z(float value) {
  
  qua_z_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Pos.qua_z)
}

// optional float qua_w = 7;
void Pos::clear_qua_w() {
  qua_w_ = 0;
}
 float Pos::qua_w() const {
  // @@protoc_insertion_point(field_get:ydpb.Pos.qua_w)
  return qua_w_;
}
 void Pos::set_qua_w(float value) {
  
  qua_w_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Pos.qua_w)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Urgent::kTempFieldNumber;
const int Urgent::kCposFieldNumber;
const int Urgent::kHposFieldNumber;
const int Urgent::kBatFieldNumber;
const int Urgent::kTidFieldNumber;
const int Urgent::kErrFieldNumber;
const int Urgent::kLastUpdatedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Urgent::Urgent()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ydpb.Urgent)
}

void Urgent::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  last_updated_ = const_cast< ::google::protobuf::Timestamp*>(&::google::protobuf::Timestamp::default_instance());
}

Urgent::Urgent(const Urgent& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ydpb.Urgent)
}

void Urgent::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  bat_ = 0;
  tid_ = 0;
  err_ = 0;
  last_updated_ = NULL;
}

Urgent::~Urgent() {
  // @@protoc_insertion_point(destructor:ydpb.Urgent)
  SharedDtor();
}

void Urgent::SharedDtor() {
  if (this != default_instance_) {
    delete last_updated_;
  }
}

void Urgent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Urgent::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Urgent_descriptor_;
}

const Urgent& Urgent::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_urgent_2eproto();
  return *default_instance_;
}

Urgent* Urgent::default_instance_ = NULL;

Urgent* Urgent::New(::google::protobuf::Arena* arena) const {
  Urgent* n = new Urgent;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Urgent::Clear() {
// @@protoc_insertion_point(message_clear_start:ydpb.Urgent)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(Urgent, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Urgent*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(bat_, tid_);
  err_ = 0;
  if (GetArenaNoVirtual() == NULL && last_updated_ != NULL) delete last_updated_;
  last_updated_ = NULL;

#undef ZR_HELPER_
#undef ZR_

  temp_.Clear();
  cpos_.Clear();
  hpos_.Clear();
}

bool Urgent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ydpb.Urgent)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated float temp = 1;
      case 1: {
        if (tag == 10) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_temp())));
        } else if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 10, input, this->mutable_temp())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_cpos;
        break;
      }

      // repeated .ydpb.Pos cpos = 2;
      case 2: {
        if (tag == 18) {
         parse_cpos:
          DO_(input->IncrementRecursionDepth());
         parse_loop_cpos:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_cpos()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_cpos;
        if (input->ExpectTag(26)) goto parse_loop_hpos;
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // repeated .ydpb.Pos hpos = 3;
      case 3: {
        if (tag == 26) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_hpos:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_hpos()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_loop_hpos;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(37)) goto parse_bat;
        break;
      }

      // optional float bat = 4;
      case 4: {
        if (tag == 37) {
         parse_bat:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &bat_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_tid;
        break;
      }

      // optional int32 tid = 5;
      case 5: {
        if (tag == 40) {
         parse_tid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &tid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_err;
        break;
      }

      // optional int32 err = 6;
      case 6: {
        if (tag == 48) {
         parse_err:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &err_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_last_updated;
        break;
      }

      // optional .google.protobuf.Timestamp last_updated = 7;
      case 7: {
        if (tag == 58) {
         parse_last_updated:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_last_updated()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ydpb.Urgent)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ydpb.Urgent)
  return false;
#undef DO_
}

void Urgent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ydpb.Urgent)
  // repeated float temp = 1;
  if (this->temp_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_temp_cached_byte_size_);
  }
  for (int i = 0; i < this->temp_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteFloatNoTag(
      this->temp(i), output);
  }

  // repeated .ydpb.Pos cpos = 2;
  for (unsigned int i = 0, n = this->cpos_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->cpos(i), output);
  }

  // repeated .ydpb.Pos hpos = 3;
  for (unsigned int i = 0, n = this->hpos_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->hpos(i), output);
  }

  // optional float bat = 4;
  if (this->bat() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->bat(), output);
  }

  // optional int32 tid = 5;
  if (this->tid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->tid(), output);
  }

  // optional int32 err = 6;
  if (this->err() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->err(), output);
  }

  // optional .google.protobuf.Timestamp last_updated = 7;
  if (this->has_last_updated()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, *this->last_updated_, output);
  }

  // @@protoc_insertion_point(serialize_end:ydpb.Urgent)
}

::google::protobuf::uint8* Urgent::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ydpb.Urgent)
  // repeated float temp = 1;
  if (this->temp_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _temp_cached_byte_size_, target);
  }
  for (int i = 0; i < this->temp_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->temp(i), target);
  }

  // repeated .ydpb.Pos cpos = 2;
  for (unsigned int i = 0, n = this->cpos_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->cpos(i), false, target);
  }

  // repeated .ydpb.Pos hpos = 3;
  for (unsigned int i = 0, n = this->hpos_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->hpos(i), false, target);
  }

  // optional float bat = 4;
  if (this->bat() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->bat(), target);
  }

  // optional int32 tid = 5;
  if (this->tid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->tid(), target);
  }

  // optional int32 err = 6;
  if (this->err() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->err(), target);
  }

  // optional .google.protobuf.Timestamp last_updated = 7;
  if (this->has_last_updated()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        7, *this->last_updated_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:ydpb.Urgent)
  return target;
}

int Urgent::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:ydpb.Urgent)
  int total_size = 0;

  // optional float bat = 4;
  if (this->bat() != 0) {
    total_size += 1 + 4;
  }

  // optional int32 tid = 5;
  if (this->tid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->tid());
  }

  // optional int32 err = 6;
  if (this->err() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->err());
  }

  // optional .google.protobuf.Timestamp last_updated = 7;
  if (this->has_last_updated()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->last_updated_);
  }

  // repeated float temp = 1;
  {
    int data_size = 0;
    data_size = 4 * this->temp_size();
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _temp_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated .ydpb.Pos cpos = 2;
  total_size += 1 * this->cpos_size();
  for (int i = 0; i < this->cpos_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->cpos(i));
  }

  // repeated .ydpb.Pos hpos = 3;
  total_size += 1 * this->hpos_size();
  for (int i = 0; i < this->hpos_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->hpos(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Urgent::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ydpb.Urgent)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Urgent* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Urgent>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ydpb.Urgent)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ydpb.Urgent)
    MergeFrom(*source);
  }
}

void Urgent::MergeFrom(const Urgent& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ydpb.Urgent)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  temp_.MergeFrom(from.temp_);
  cpos_.MergeFrom(from.cpos_);
  hpos_.MergeFrom(from.hpos_);
  if (from.bat() != 0) {
    set_bat(from.bat());
  }
  if (from.tid() != 0) {
    set_tid(from.tid());
  }
  if (from.err() != 0) {
    set_err(from.err());
  }
  if (from.has_last_updated()) {
    mutable_last_updated()->::google::protobuf::Timestamp::MergeFrom(from.last_updated());
  }
}

void Urgent::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ydpb.Urgent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Urgent::CopyFrom(const Urgent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ydpb.Urgent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Urgent::IsInitialized() const {

  return true;
}

void Urgent::Swap(Urgent* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Urgent::InternalSwap(Urgent* other) {
  temp_.UnsafeArenaSwap(&other->temp_);
  cpos_.UnsafeArenaSwap(&other->cpos_);
  hpos_.UnsafeArenaSwap(&other->hpos_);
  std::swap(bat_, other->bat_);
  std::swap(tid_, other->tid_);
  std::swap(err_, other->err_);
  std::swap(last_updated_, other->last_updated_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Urgent::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Urgent_descriptor_;
  metadata.reflection = Urgent_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Urgent

// repeated float temp = 1;
int Urgent::temp_size() const {
  return temp_.size();
}
void Urgent::clear_temp() {
  temp_.Clear();
}
 float Urgent::temp(int index) const {
  // @@protoc_insertion_point(field_get:ydpb.Urgent.temp)
  return temp_.Get(index);
}
 void Urgent::set_temp(int index, float value) {
  temp_.Set(index, value);
  // @@protoc_insertion_point(field_set:ydpb.Urgent.temp)
}
 void Urgent::add_temp(float value) {
  temp_.Add(value);
  // @@protoc_insertion_point(field_add:ydpb.Urgent.temp)
}
 const ::google::protobuf::RepeatedField< float >&
Urgent::temp() const {
  // @@protoc_insertion_point(field_list:ydpb.Urgent.temp)
  return temp_;
}
 ::google::protobuf::RepeatedField< float >*
Urgent::mutable_temp() {
  // @@protoc_insertion_point(field_mutable_list:ydpb.Urgent.temp)
  return &temp_;
}

// repeated .ydpb.Pos cpos = 2;
int Urgent::cpos_size() const {
  return cpos_.size();
}
void Urgent::clear_cpos() {
  cpos_.Clear();
}
const ::ydpb::Pos& Urgent::cpos(int index) const {
  // @@protoc_insertion_point(field_get:ydpb.Urgent.cpos)
  return cpos_.Get(index);
}
::ydpb::Pos* Urgent::mutable_cpos(int index) {
  // @@protoc_insertion_point(field_mutable:ydpb.Urgent.cpos)
  return cpos_.Mutable(index);
}
::ydpb::Pos* Urgent::add_cpos() {
  // @@protoc_insertion_point(field_add:ydpb.Urgent.cpos)
  return cpos_.Add();
}
::google::protobuf::RepeatedPtrField< ::ydpb::Pos >*
Urgent::mutable_cpos() {
  // @@protoc_insertion_point(field_mutable_list:ydpb.Urgent.cpos)
  return &cpos_;
}
const ::google::protobuf::RepeatedPtrField< ::ydpb::Pos >&
Urgent::cpos() const {
  // @@protoc_insertion_point(field_list:ydpb.Urgent.cpos)
  return cpos_;
}

// repeated .ydpb.Pos hpos = 3;
int Urgent::hpos_size() const {
  return hpos_.size();
}
void Urgent::clear_hpos() {
  hpos_.Clear();
}
const ::ydpb::Pos& Urgent::hpos(int index) const {
  // @@protoc_insertion_point(field_get:ydpb.Urgent.hpos)
  return hpos_.Get(index);
}
::ydpb::Pos* Urgent::mutable_hpos(int index) {
  // @@protoc_insertion_point(field_mutable:ydpb.Urgent.hpos)
  return hpos_.Mutable(index);
}
::ydpb::Pos* Urgent::add_hpos() {
  // @@protoc_insertion_point(field_add:ydpb.Urgent.hpos)
  return hpos_.Add();
}
::google::protobuf::RepeatedPtrField< ::ydpb::Pos >*
Urgent::mutable_hpos() {
  // @@protoc_insertion_point(field_mutable_list:ydpb.Urgent.hpos)
  return &hpos_;
}
const ::google::protobuf::RepeatedPtrField< ::ydpb::Pos >&
Urgent::hpos() const {
  // @@protoc_insertion_point(field_list:ydpb.Urgent.hpos)
  return hpos_;
}

// optional float bat = 4;
void Urgent::clear_bat() {
  bat_ = 0;
}
 float Urgent::bat() const {
  // @@protoc_insertion_point(field_get:ydpb.Urgent.bat)
  return bat_;
}
 void Urgent::set_bat(float value) {
  
  bat_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Urgent.bat)
}

// optional int32 tid = 5;
void Urgent::clear_tid() {
  tid_ = 0;
}
 ::google::protobuf::int32 Urgent::tid() const {
  // @@protoc_insertion_point(field_get:ydpb.Urgent.tid)
  return tid_;
}
 void Urgent::set_tid(::google::protobuf::int32 value) {
  
  tid_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Urgent.tid)
}

// optional int32 err = 6;
void Urgent::clear_err() {
  err_ = 0;
}
 ::google::protobuf::int32 Urgent::err() const {
  // @@protoc_insertion_point(field_get:ydpb.Urgent.err)
  return err_;
}
 void Urgent::set_err(::google::protobuf::int32 value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Urgent.err)
}

// optional .google.protobuf.Timestamp last_updated = 7;
bool Urgent::has_last_updated() const {
  return !_is_default_instance_ && last_updated_ != NULL;
}
void Urgent::clear_last_updated() {
  if (GetArenaNoVirtual() == NULL && last_updated_ != NULL) delete last_updated_;
  last_updated_ = NULL;
}
const ::google::protobuf::Timestamp& Urgent::last_updated() const {
  // @@protoc_insertion_point(field_get:ydpb.Urgent.last_updated)
  return last_updated_ != NULL ? *last_updated_ : *default_instance_->last_updated_;
}
::google::protobuf::Timestamp* Urgent::mutable_last_updated() {
  
  if (last_updated_ == NULL) {
    last_updated_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:ydpb.Urgent.last_updated)
  return last_updated_;
}
::google::protobuf::Timestamp* Urgent::release_last_updated() {
  // @@protoc_insertion_point(field_release:ydpb.Urgent.last_updated)
  
  ::google::protobuf::Timestamp* temp = last_updated_;
  last_updated_ = NULL;
  return temp;
}
void Urgent::set_allocated_last_updated(::google::protobuf::Timestamp* last_updated) {
  delete last_updated_;
  if (last_updated != NULL && last_updated->GetArena() != NULL) {
    ::google::protobuf::Timestamp* new_last_updated = new ::google::protobuf::Timestamp;
    new_last_updated->CopyFrom(*last_updated);
    last_updated = new_last_updated;
  }
  last_updated_ = last_updated;
  if (last_updated) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:ydpb.Urgent.last_updated)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ydpb

// @@protoc_insertion_point(global_scope)
