// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: urgent.proto

#ifndef PROTOBUF_urgent_2eproto__INCLUDED
#define PROTOBUF_urgent_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)

namespace ydpb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_urgent_2eproto();
void protobuf_AssignDesc_urgent_2eproto();
void protobuf_ShutdownFile_urgent_2eproto();

class Pos;
class Urgent;

// ===================================================================

class Pos : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ydpb.Pos) */ {
 public:
  Pos();
  virtual ~Pos();

  Pos(const Pos& from);

  inline Pos& operator=(const Pos& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Pos& default_instance();

  void Swap(Pos* other);

  // implements Message ----------------------------------------------

  inline Pos* New() const { return New(NULL); }

  Pos* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Pos& from);
  void MergeFrom(const Pos& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Pos* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float pos_x = 1;
  void clear_pos_x();
  static const int kPosXFieldNumber = 1;
  float pos_x() const;
  void set_pos_x(float value);

  // optional float pos_y = 2;
  void clear_pos_y();
  static const int kPosYFieldNumber = 2;
  float pos_y() const;
  void set_pos_y(float value);

  // optional float pos_z = 3;
  void clear_pos_z();
  static const int kPosZFieldNumber = 3;
  float pos_z() const;
  void set_pos_z(float value);

  // optional float qua_x = 4;
  void clear_qua_x();
  static const int kQuaXFieldNumber = 4;
  float qua_x() const;
  void set_qua_x(float value);

  // optional float qua_y = 5;
  void clear_qua_y();
  static const int kQuaYFieldNumber = 5;
  float qua_y() const;
  void set_qua_y(float value);

  // optional float qua_z = 6;
  void clear_qua_z();
  static const int kQuaZFieldNumber = 6;
  float qua_z() const;
  void set_qua_z(float value);

  // optional float qua_w = 7;
  void clear_qua_w();
  static const int kQuaWFieldNumber = 7;
  float qua_w() const;
  void set_qua_w(float value);

  // @@protoc_insertion_point(class_scope:ydpb.Pos)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  float pos_x_;
  float pos_y_;
  float pos_z_;
  float qua_x_;
  float qua_y_;
  float qua_z_;
  float qua_w_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_urgent_2eproto();
  friend void protobuf_AssignDesc_urgent_2eproto();
  friend void protobuf_ShutdownFile_urgent_2eproto();

  void InitAsDefaultInstance();
  static Pos* default_instance_;
};
// -------------------------------------------------------------------

class Urgent : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ydpb.Urgent) */ {
 public:
  Urgent();
  virtual ~Urgent();

  Urgent(const Urgent& from);

  inline Urgent& operator=(const Urgent& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Urgent& default_instance();

  void Swap(Urgent* other);

  // implements Message ----------------------------------------------

  inline Urgent* New() const { return New(NULL); }

  Urgent* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Urgent& from);
  void MergeFrom(const Urgent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Urgent* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float temp = 1;
  int temp_size() const;
  void clear_temp();
  static const int kTempFieldNumber = 1;
  float temp(int index) const;
  void set_temp(int index, float value);
  void add_temp(float value);
  const ::google::protobuf::RepeatedField< float >&
      temp() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_temp();

  // repeated .ydpb.Pos cpos = 2;
  int cpos_size() const;
  void clear_cpos();
  static const int kCposFieldNumber = 2;
  const ::ydpb::Pos& cpos(int index) const;
  ::ydpb::Pos* mutable_cpos(int index);
  ::ydpb::Pos* add_cpos();
  ::google::protobuf::RepeatedPtrField< ::ydpb::Pos >*
      mutable_cpos();
  const ::google::protobuf::RepeatedPtrField< ::ydpb::Pos >&
      cpos() const;

  // repeated .ydpb.Pos hpos = 3;
  int hpos_size() const;
  void clear_hpos();
  static const int kHposFieldNumber = 3;
  const ::ydpb::Pos& hpos(int index) const;
  ::ydpb::Pos* mutable_hpos(int index);
  ::ydpb::Pos* add_hpos();
  ::google::protobuf::RepeatedPtrField< ::ydpb::Pos >*
      mutable_hpos();
  const ::google::protobuf::RepeatedPtrField< ::ydpb::Pos >&
      hpos() const;

  // optional float bat = 4;
  void clear_bat();
  static const int kBatFieldNumber = 4;
  float bat() const;
  void set_bat(float value);

  // optional int32 tid = 5;
  void clear_tid();
  static const int kTidFieldNumber = 5;
  ::google::protobuf::int32 tid() const;
  void set_tid(::google::protobuf::int32 value);

  // optional int32 err = 6;
  void clear_err();
  static const int kErrFieldNumber = 6;
  ::google::protobuf::int32 err() const;
  void set_err(::google::protobuf::int32 value);

  // optional .google.protobuf.Timestamp last_updated = 7;
  bool has_last_updated() const;
  void clear_last_updated();
  static const int kLastUpdatedFieldNumber = 7;
  const ::google::protobuf::Timestamp& last_updated() const;
  ::google::protobuf::Timestamp* mutable_last_updated();
  ::google::protobuf::Timestamp* release_last_updated();
  void set_allocated_last_updated(::google::protobuf::Timestamp* last_updated);

  // @@protoc_insertion_point(class_scope:ydpb.Urgent)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedField< float > temp_;
  mutable int _temp_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::ydpb::Pos > cpos_;
  ::google::protobuf::RepeatedPtrField< ::ydpb::Pos > hpos_;
  float bat_;
  ::google::protobuf::int32 tid_;
  ::google::protobuf::Timestamp* last_updated_;
  ::google::protobuf::int32 err_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_urgent_2eproto();
  friend void protobuf_AssignDesc_urgent_2eproto();
  friend void protobuf_ShutdownFile_urgent_2eproto();

  void InitAsDefaultInstance();
  static Urgent* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Pos

// optional float pos_x = 1;
inline void Pos::clear_pos_x() {
  pos_x_ = 0;
}
inline float Pos::pos_x() const {
  // @@protoc_insertion_point(field_get:ydpb.Pos.pos_x)
  return pos_x_;
}
inline void Pos::set_pos_x(float value) {
  
  pos_x_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Pos.pos_x)
}

// optional float pos_y = 2;
inline void Pos::clear_pos_y() {
  pos_y_ = 0;
}
inline float Pos::pos_y() const {
  // @@protoc_insertion_point(field_get:ydpb.Pos.pos_y)
  return pos_y_;
}
inline void Pos::set_pos_y(float value) {
  
  pos_y_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Pos.pos_y)
}

// optional float pos_z = 3;
inline void Pos::clear_pos_z() {
  pos_z_ = 0;
}
inline float Pos::pos_z() const {
  // @@protoc_insertion_point(field_get:ydpb.Pos.pos_z)
  return pos_z_;
}
inline void Pos::set_pos_z(float value) {
  
  pos_z_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Pos.pos_z)
}

// optional float qua_x = 4;
inline void Pos::clear_qua_x() {
  qua_x_ = 0;
}
inline float Pos::qua_x() const {
  // @@protoc_insertion_point(field_get:ydpb.Pos.qua_x)
  return qua_x_;
}
inline void Pos::set_qua_x(float value) {
  
  qua_x_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Pos.qua_x)
}

// optional float qua_y = 5;
inline void Pos::clear_qua_y() {
  qua_y_ = 0;
}
inline float Pos::qua_y() const {
  // @@protoc_insertion_point(field_get:ydpb.Pos.qua_y)
  return qua_y_;
}
inline void Pos::set_qua_y(float value) {
  
  qua_y_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Pos.qua_y)
}

// optional float qua_z = 6;
inline void Pos::clear_qua_z() {
  qua_z_ = 0;
}
inline float Pos::qua_z() const {
  // @@protoc_insertion_point(field_get:ydpb.Pos.qua_z)
  return qua_z_;
}
inline void Pos::set_qua_z(float value) {
  
  qua_z_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Pos.qua_z)
}

// optional float qua_w = 7;
inline void Pos::clear_qua_w() {
  qua_w_ = 0;
}
inline float Pos::qua_w() const {
  // @@protoc_insertion_point(field_get:ydpb.Pos.qua_w)
  return qua_w_;
}
inline void Pos::set_qua_w(float value) {
  
  qua_w_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Pos.qua_w)
}

// -------------------------------------------------------------------

// Urgent

// repeated float temp = 1;
inline int Urgent::temp_size() const {
  return temp_.size();
}
inline void Urgent::clear_temp() {
  temp_.Clear();
}
inline float Urgent::temp(int index) const {
  // @@protoc_insertion_point(field_get:ydpb.Urgent.temp)
  return temp_.Get(index);
}
inline void Urgent::set_temp(int index, float value) {
  temp_.Set(index, value);
  // @@protoc_insertion_point(field_set:ydpb.Urgent.temp)
}
inline void Urgent::add_temp(float value) {
  temp_.Add(value);
  // @@protoc_insertion_point(field_add:ydpb.Urgent.temp)
}
inline const ::google::protobuf::RepeatedField< float >&
Urgent::temp() const {
  // @@protoc_insertion_point(field_list:ydpb.Urgent.temp)
  return temp_;
}
inline ::google::protobuf::RepeatedField< float >*
Urgent::mutable_temp() {
  // @@protoc_insertion_point(field_mutable_list:ydpb.Urgent.temp)
  return &temp_;
}

// repeated .ydpb.Pos cpos = 2;
inline int Urgent::cpos_size() const {
  return cpos_.size();
}
inline void Urgent::clear_cpos() {
  cpos_.Clear();
}
inline const ::ydpb::Pos& Urgent::cpos(int index) const {
  // @@protoc_insertion_point(field_get:ydpb.Urgent.cpos)
  return cpos_.Get(index);
}
inline ::ydpb::Pos* Urgent::mutable_cpos(int index) {
  // @@protoc_insertion_point(field_mutable:ydpb.Urgent.cpos)
  return cpos_.Mutable(index);
}
inline ::ydpb::Pos* Urgent::add_cpos() {
  // @@protoc_insertion_point(field_add:ydpb.Urgent.cpos)
  return cpos_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ydpb::Pos >*
Urgent::mutable_cpos() {
  // @@protoc_insertion_point(field_mutable_list:ydpb.Urgent.cpos)
  return &cpos_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ydpb::Pos >&
Urgent::cpos() const {
  // @@protoc_insertion_point(field_list:ydpb.Urgent.cpos)
  return cpos_;
}

// repeated .ydpb.Pos hpos = 3;
inline int Urgent::hpos_size() const {
  return hpos_.size();
}
inline void Urgent::clear_hpos() {
  hpos_.Clear();
}
inline const ::ydpb::Pos& Urgent::hpos(int index) const {
  // @@protoc_insertion_point(field_get:ydpb.Urgent.hpos)
  return hpos_.Get(index);
}
inline ::ydpb::Pos* Urgent::mutable_hpos(int index) {
  // @@protoc_insertion_point(field_mutable:ydpb.Urgent.hpos)
  return hpos_.Mutable(index);
}
inline ::ydpb::Pos* Urgent::add_hpos() {
  // @@protoc_insertion_point(field_add:ydpb.Urgent.hpos)
  return hpos_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ydpb::Pos >*
Urgent::mutable_hpos() {
  // @@protoc_insertion_point(field_mutable_list:ydpb.Urgent.hpos)
  return &hpos_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ydpb::Pos >&
Urgent::hpos() const {
  // @@protoc_insertion_point(field_list:ydpb.Urgent.hpos)
  return hpos_;
}

// optional float bat = 4;
inline void Urgent::clear_bat() {
  bat_ = 0;
}
inline float Urgent::bat() const {
  // @@protoc_insertion_point(field_get:ydpb.Urgent.bat)
  return bat_;
}
inline void Urgent::set_bat(float value) {
  
  bat_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Urgent.bat)
}

// optional int32 tid = 5;
inline void Urgent::clear_tid() {
  tid_ = 0;
}
inline ::google::protobuf::int32 Urgent::tid() const {
  // @@protoc_insertion_point(field_get:ydpb.Urgent.tid)
  return tid_;
}
inline void Urgent::set_tid(::google::protobuf::int32 value) {
  
  tid_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Urgent.tid)
}

// optional int32 err = 6;
inline void Urgent::clear_err() {
  err_ = 0;
}
inline ::google::protobuf::int32 Urgent::err() const {
  // @@protoc_insertion_point(field_get:ydpb.Urgent.err)
  return err_;
}
inline void Urgent::set_err(::google::protobuf::int32 value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:ydpb.Urgent.err)
}

// optional .google.protobuf.Timestamp last_updated = 7;
inline bool Urgent::has_last_updated() const {
  return !_is_default_instance_ && last_updated_ != NULL;
}
inline void Urgent::clear_last_updated() {
  if (GetArenaNoVirtual() == NULL && last_updated_ != NULL) delete last_updated_;
  last_updated_ = NULL;
}
inline const ::google::protobuf::Timestamp& Urgent::last_updated() const {
  // @@protoc_insertion_point(field_get:ydpb.Urgent.last_updated)
  return last_updated_ != NULL ? *last_updated_ : *default_instance_->last_updated_;
}
inline ::google::protobuf::Timestamp* Urgent::mutable_last_updated() {
  
  if (last_updated_ == NULL) {
    last_updated_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:ydpb.Urgent.last_updated)
  return last_updated_;
}
inline ::google::protobuf::Timestamp* Urgent::release_last_updated() {
  // @@protoc_insertion_point(field_release:ydpb.Urgent.last_updated)
  
  ::google::protobuf::Timestamp* temp = last_updated_;
  last_updated_ = NULL;
  return temp;
}
inline void Urgent::set_allocated_last_updated(::google::protobuf::Timestamp* last_updated) {
  delete last_updated_;
  if (last_updated != NULL && last_updated->GetArena() != NULL) {
    ::google::protobuf::Timestamp* new_last_updated = new ::google::protobuf::Timestamp;
    new_last_updated->CopyFrom(*last_updated);
    last_updated = new_last_updated;
  }
  last_updated_ = last_updated;
  if (last_updated) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:ydpb.Urgent.last_updated)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ydpb

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_urgent_2eproto__INCLUDED
